project:
  type: website
  output-dir: ../docs


website:
  page-navigation: true
  search: false
  page-footer:
    border: false
    background: transparent
    foreground: DimGray
    #left: Left content
    #right: Right content
  navbar:
    background: transparent
    pinned: true
    left:
      - file: index.qmd
        text: Home
      - file: "diabetes.qmd#overview"
        text: Overview  
      - file: "diabetes.qmd#intro"
        text: Introduction
      - text: Analysis
        menu:
        - text: Exploratory Data Analysis
          href: "diabetes.qmd#eda"
        - text: Baseline Model
          href: "diabetes.qmd#baselinemodel"
        - text: Hyperparameter Tuning
          href: "diabetes.qmd#hyper"
        - text: Stacking Ensemble Evaluation
          href: "diabetes.qmd#stacking"
        - text: Best Model
          href: "diabetes.qmd#bestmodel"
      - text: Deployment
        href: "diabetes.qmd#deployment"
      - text: Conclusion
        href: "diabetes.qmd#conclusion"

    right:
      - icon: github
        href: https://github.com/chaishekar/Diabetes-Prediction-App/


        

format:
  html:
    theme: 
      - styles.scss
    toc: false

editor: visual
